import { MenuItem, Category } from '@/types';

export const menuItems: MenuItem[] = [
  // Hot Appetizers & Soups
  { id: 'ha1', nameAr: 'أرز أبيض', nameEn: 'White Rice', price: 15, category: 'hotAppetizers' },
  { id: 'ha2', nameAr: 'شوربة مأكولات بحرية', nameEn: 'Sea Food Soup', price: 28, category: 'hotAppetizers' },
  { id: 'ha3', nameAr: 'حمص مع اللحم', nameEn: 'Hummus with Meat', price: 30, category: 'hotAppetizers' },
  { id: 'ha4', nameAr: 'شوربة فطر', nameEn: 'Mushroom Soup', price: 25, category: 'hotAppetizers' },
  { id: 'ha5', nameAr: 'كبة مقلية', nameEn: 'Fried Kubbah', price: 25, category: 'hotAppetizers' },
  { id: 'ha6', nameAr: 'شوربة دجاج', nameEn: 'Chicken Soup', price: 25, category: 'hotAppetizers' },
  { id: 'ha7', nameAr: 'سجق لف', nameEn: 'Sujuq Roll', price: 25, category: 'hotAppetizers' },
  { id: 'ha8', nameAr: 'بطاطس حارة', nameEn: 'Spicy Potato', price: 25, category: 'hotAppetizers' },
  { id: 'ha9', nameAr: 'بطاطس مقلية', nameEn: 'French Fried', price: 20, category: 'hotAppetizers' },
  { id: 'ha10', nameAr: 'أصابع جبنة', nameEn: 'Cheese Fingers', price: 25, category: 'hotAppetizers' },
  
  // Cold Appetizers & Salads
  { id: 'ca1', nameAr: 'ورق عنب', nameEn: 'Grape Leaves', price: 20, category: 'coldAppetizers' },
  { id: 'ca2', nameAr: 'تبولة', nameEn: 'Tabouleh', price: 26, category: 'coldAppetizers' },
  { id: 'ca3', nameAr: 'حمص', nameEn: 'Hummus', price: 20, category: 'coldAppetizers' },
  { id: 'ca4', nameAr: 'فتوش', nameEn: 'Fattoush', price: 28, category: 'coldAppetizers' },
  { id: 'ca5', nameAr: 'متبل', nameEn: 'Mutabal', price: 22, category: 'coldAppetizers' },
  { id: 'ca6', nameAr: 'سلطة روكا', nameEn: 'Rocca Salad', price: 25, category: 'coldAppetizers' },
  { id: 'ca7', nameAr: 'سلطة قيصر', nameEn: 'Caesar Salad', price: 32, category: 'coldAppetizers' },
  { id: 'ca8', nameAr: 'سلطة كستانا بالفيتا', nameEn: 'Castana Salad with Feta', price: 28, category: 'coldAppetizers' },
  
  // Pizza & Pasta
  { id: 'pp1', nameAr: 'بيتزا كستانا', nameEn: 'Castana Pizza', price: 35, category: 'pizzaPasta' },
  { id: 'pp2', nameAr: 'فيتوتشيني ألفريدو', nameEn: 'Alfredo Fettuccine', price: 45, category: 'pizzaPasta' },
  { id: 'pp3', nameAr: 'بيتزا شاورما', nameEn: 'Shawerma Pizza', price: 33, category: 'pizzaPasta' },
  { id: 'pp4', nameAr: 'سباغيتي بولونيز', nameEn: 'Spaghetti Bolognese', price: 43, category: 'pizzaPasta' },
  { id: 'pp5', nameAr: 'بيتزا بيبروني', nameEn: 'Pepperoni Pizza', price: 33, category: 'pizzaPasta' },
  { id: 'pp6', nameAr: 'فيتوتشيني روبيان', nameEn: 'Shrimp Fettuccine', price: 48, category: 'pizzaPasta' },
  { id: 'pp7', nameAr: 'بيتزا خضار', nameEn: 'Vegetable Pizza', price: 28, category: 'pizzaPasta' },
  { id: 'pp8', nameAr: 'بيني أرابياتا', nameEn: 'Penne Arrabiata', price: 40, category: 'pizzaPasta' },
  { id: 'pp9', nameAr: 'بيتزا مارغريتا', nameEn: 'Margherita Pizza', price: 26, category: 'pizzaPasta' },
  
  // Sandwiches
  { id: 's1', nameAr: 'دجاج مكسيكي', nameEn: 'Mexican Chicken', price: 32, category: 'sandwiches' },
  { id: 's2', nameAr: 'شاورما', nameEn: 'Shawerma', price: 30, category: 'sandwiches' },
  { id: 's3', nameAr: 'فيليه ستيك', nameEn: 'Fillet Steak', price: 35, category: 'sandwiches' },
  { id: 's4', nameAr: 'ستيك إيطالي', nameEn: 'Italian Steak', price: 38, category: 'sandwiches' },
  { id: 's5', nameAr: 'كيساديلاس', nameEn: 'Quesadillas', price: 35, category: 'sandwiches' },
  { id: 's6', nameAr: 'فاهيتا دجاج', nameEn: 'Chicken Fajitas', price: 30, category: 'sandwiches' },
  
  // Main Courses (Chicken & Meat)
  { id: 'mc1', nameAr: 'ستيك حسب الطلب', nameEn: 'Steak On Demand', price: 70, category: 'mainCourses' },
  { id: 'mc2', nameAr: 'إسكالوب دجاج', nameEn: 'Chicken Escalope', price: 55, category: 'mainCourses' },
  { id: 'mc3', nameAr: 'كافيه دو باريس', nameEn: 'Cafe De Paris', price: 65, category: 'mainCourses' },
  { id: 'mc4', nameAr: 'بولو أوليفيانو', nameEn: 'Polo Oliviano', price: 50, category: 'mainCourses' },
  { id: 'mc5', nameAr: 'بان جريل بفطر كريمي', nameEn: 'Pan Grill Creamy Mushroom', price: 60, category: 'mainCourses' },
  { id: 'mc6', nameAr: 'كاري دجاج مع الأرز', nameEn: 'Chicken Curry With Rice', price: 55, category: 'mainCourses' },
  { id: 'mc7', nameAr: 'فاهيتا دجاج مع الأرز', nameEn: 'Chicken Fajita With Rice', price: 55, category: 'mainCourses' },
  
  // Grilled
  { id: 'g1', nameAr: 'لحم أصول', nameEn: 'Meat Awsal', price: 65, category: 'grilled' },
  { id: 'g2', nameAr: 'كباب لحم', nameEn: 'Meat Kebab', price: 45, category: 'grilled' },
  { id: 'g3', nameAr: 'مشكل مشوي', nameEn: 'Mixed Grill', price: 60, category: 'grilled' },
  { id: 'g4', nameAr: 'عرباوي', nameEn: 'Arayes', price: 45, category: 'grilled' },
  { id: 'g5', nameAr: 'مجوجة', nameEn: 'Majuga', price: 60, category: 'grilled' },
  { id: 'g6', nameAr: 'كبة مشوية', nameEn: 'Grilled Kibbeh', price: 45, category: 'grilled' },
  { id: 'g7', nameAr: 'تاووك', nameEn: 'Tawook', price: 45, category: 'grilled' },
  { id: 'g8', nameAr: 'جبنة كردية', nameEn: 'Kurdish Cheese', price: 40, category: 'grilled' },
  
  // Breakfast
  { id: 'b1', nameAr: 'حلومي مشوي', nameEn: 'Grilled Halloume', price: 28, category: 'breakfast' },
  { id: 'b2', nameAr: 'فول بالخضار', nameEn: 'Bean with Vegetables', price: 18, category: 'breakfast' },
  { id: 'b3', nameAr: 'حمص فتة', nameEn: 'Homos Fattah', price: 26, category: 'breakfast' },
  { id: 'b4', nameAr: 'مناقيش عكاري', nameEn: 'Manoushe Akkawi Cheese', price: 18, category: 'breakfast' },
  { id: 'b5', nameAr: 'كبدة', nameEn: 'Kebdah', price: 25, category: 'breakfast' },
  { id: 'b6', nameAr: 'أومليت', nameEn: 'Omlet', price: 17, category: 'breakfast' },
  { id: 'b7', nameAr: 'شكشوكة', nameEn: 'Shakshouka', price: 20, category: 'breakfast' },
  { id: 'b8', nameAr: 'لبنة', nameEn: 'Labnah', price: 16, category: 'breakfast' },
  { id: 'b9', nameAr: 'مناقيش جبنة مشكلة', nameEn: 'Manoushe Mixed Cheese', price: 20, category: 'breakfast' },
  { id: 'b10', nameAr: 'بيض مسلوق', nameEn: 'Boiled Eggs', price: 14, category: 'breakfast' },
  { id: 'b11', nameAr: 'مناقيش زعتر', nameEn: 'Manoushe Zattar', price: 14, category: 'breakfast' },
  { id: 'b12', nameAr: 'زيتون', nameEn: 'Olives', price: 13, category: 'breakfast' },
  { id: 'b13', nameAr: 'خضار مشكلة', nameEn: 'Mixed Vegetables', price: 12, category: 'breakfast' },
  
  // Sweets & Ice Cream
  { id: 'sw1', nameAr: 'كوكيز مع آيس كريم', nameEn: 'Cookies with Ice Cream', price: 30, category: 'sweets' },
  { id: 'sw2', nameAr: 'كيكة الجزر', nameEn: 'The Cake of Carrots', price: 23, category: 'sweets' },
  { id: 'sw3', nameAr: 'فوندانة شوكولاتة مع آيس كريم', nameEn: 'Chocolate Fondue & Ice Cream', price: 30, category: 'sweets' },
  { id: 'sw4', nameAr: 'كيكة شوكولاتة ألمانية', nameEn: 'Chocolate German Cake', price: 23, category: 'sweets' },
  { id: 'sw5', nameAr: 'مكسرات مشكلة', nameEn: 'Mixed Nuts', price: 28, category: 'sweets' },
  { id: 'sw6', nameAr: 'نوتيلا ساج', nameEn: 'Nutella Saj', price: 21, category: 'sweets' },
  { id: 'sw7', nameAr: 'معمول بالجبنة', nameEn: 'Maamoul with Cheese', price: 20, category: 'sweets' },
  
  // Hot Drinks
  { id: 'hd1', nameAr: 'قهوة فرنسية مزدوجة', nameEn: 'Double French Coffee', price: 28, category: 'hotDrinks' },
  { id: 'hd2', nameAr: 'إسبريسو', nameEn: 'Espresso', price: 17, category: 'hotDrinks' },
  { id: 'hd3', nameAr: 'شوكولاتة ساخنة', nameEn: 'Hot Chocolate', price: 27, category: 'hotDrinks' },
  { id: 'hd4', nameAr: 'إسبريسو مزدوج', nameEn: 'Double Espresso', price: 20, category: 'hotDrinks' },
  { id: 'hd5', nameAr: 'لاتيه كافيه', nameEn: 'Latte Cafe', price: 25, category: 'hotDrinks' },
  { id: 'hd6', nameAr: 'قهوة تركية', nameEn: 'Turkish Coffee', price: 16, category: 'hotDrinks' },
  { id: 'hd7', nameAr: 'موكا', nameEn: 'Mocha', price: 25, category: 'hotDrinks' },
  { id: 'hd8', nameAr: 'قهوة تركية مزدوجة', nameEn: 'Double Turkish Coffee', price: 20, category: 'hotDrinks' },
  { id: 'hd9', nameAr: 'كابوتشينو', nameEn: 'Cappuccino', price: 24, category: 'hotDrinks' },
  { id: 'hd10', nameAr: 'قهوة فرنسية', nameEn: 'French Coffee', price: 20, category: 'hotDrinks' },
  { id: 'hd11', nameAr: 'موكا ميكاتو مزدوج', nameEn: 'Double Mocha Michato', price: 23, category: 'hotDrinks' },
  { id: 'hd12', nameAr: 'أمريكانو', nameEn: 'Americano', price: 20, category: 'hotDrinks' },
  { id: 'hd13', nameAr: 'قهوة إيطالية', nameEn: 'Italian Coffee', price: 22, category: 'hotDrinks' },
  { id: 'hd14', nameAr: 'ميكاتو', nameEn: 'Mikato', price: 21, category: 'hotDrinks' },
  
  // Cold Drinks & Milkshakes
  { id: 'cd1', nameAr: 'كوكتيل كستانا', nameEn: 'Castanacocktail', price: 37, category: 'coldDrinks' },
  { id: 'cd2', nameAr: 'فرابتشينو', nameEn: 'Frappuccino', price: 25, category: 'coldDrinks' },
  { id: 'cd3', nameAr: 'ميلك شيك لوتس', nameEn: 'Lotus Milkshake', price: 32, category: 'coldDrinks' },
  { id: 'cd4', nameAr: 'ريد لاند', nameEn: 'Red Land', price: 25, category: 'coldDrinks' },
  { id: 'cd5', nameAr: 'ميلك شيك أوريو', nameEn: 'Oreo Milkshake', price: 32, category: 'coldDrinks' },
  { id: 'cd6', nameAr: 'برتقال', nameEn: 'Orange', price: 25, category: 'coldDrinks' },
  { id: 'cd7', nameAr: 'ميلك شيك نوتيلا', nameEn: 'Nutella Milkshake', price: 32, category: 'coldDrinks' },
  { id: 'cd8', nameAr: 'ليمون', nameEn: 'Lemon', price: 25, category: 'coldDrinks' },
  { id: 'cd9', nameAr: 'ميلك شيك فانيلا', nameEn: 'Vanilla Milkshake', price: 30, category: 'coldDrinks' },
  { id: 'cd10', nameAr: 'آيس أمريكانو', nameEn: 'Ice American', price: 19, category: 'coldDrinks' },
  { id: 'cd11', nameAr: 'ميلك شيك فراولة', nameEn: 'Strawberry Milkshake', price: 30, category: 'coldDrinks' },
  { id: 'cd12', nameAr: 'باريه', nameEn: 'Beret', price: 16, category: 'coldDrinks' },
  { id: 'cd13', nameAr: 'جرين لاند', nameEn: 'Green Land', price: 29, category: 'coldDrinks' },
  { id: 'cd14', nameAr: 'ريد بول', nameEn: 'Red Bull', price: 22, category: 'coldDrinks' },
  { id: 'cd15', nameAr: 'جامايكا', nameEn: 'Jamaica', price: 28, category: 'coldDrinks' },
  { id: 'cd16', nameAr: 'مشروبات غازية', nameEn: 'Soft Drinks', price: 8, category: 'coldDrinks' },
  { id: 'cd17', nameAr: 'سبانيش لاتيه', nameEn: 'Spanish Latte', price: 28, category: 'coldDrinks' },
  { id: 'cd18', nameAr: 'مياه', nameEn: 'Water', price: 4, category: 'coldDrinks' },
  { id: 'cd19', nameAr: 'إست برتقال', nameEn: 'Est Orange', price: 28, category: 'coldDrinks' },
  { id: 'cd20', nameAr: 'موهيتو فراولة', nameEn: 'Strawberry Mojito', price: 30, category: 'coldDrinks' },
  { id: 'cd21', nameAr: 'ليمون نعناع', nameEn: 'Lemon Mint', price: 26, category: 'coldDrinks' },
  { id: 'cd22', nameAr: 'جزر', nameEn: 'Carrots', price: 26, category: 'coldDrinks' },
  { id: 'cd23', nameAr: 'كوكتيل فرنسي', nameEn: 'French Cocktail', price: 26, category: 'coldDrinks' },
  { id: 'cd24', nameAr: 'كولد موكا', nameEn: 'Cold Mocha', price: 26, category: 'coldDrinks' },
];

export const categories: { [key in Category]: { ar: string; en: string } } = {
  hotAppetizers: { ar: 'المقبلات والشوربات الساخنة', en: 'Hot Appetizers & Soups' },
  coldAppetizers: { ar: 'المقبلات والسلطات الباردة', en: 'Cold Appetizers & Salads' },
  pizzaPasta: { ar: 'البيتزا والباستا', en: 'Pizza & Pasta' },
  sandwiches: { ar: 'السندوتشات', en: 'Sandwiches' },
  mainCourses: { ar: 'الأطباق الرئيسية', en: 'Main Courses' },
  grilled: { ar: 'المشويات', en: 'Grilled' },
  breakfast: { ar: 'الإفطار', en: 'Breakfast' },
  sweets: { ar: 'الحلويات والآيس كريم', en: 'Sweets & Ice Cream' },
  hotDrinks: { ar: 'المشروبات الساخنة', en: 'Hot Drinks' },
  coldDrinks: { ar: 'المشروبات الباردة والميلك شيك', en: 'Cold Drinks & Milkshakes' },
};
